### PR TITLE
#135 Single command to build project

### LINKED ISSUE #135: Single command to build project
As for now, a developer/user needs to run several commands to have LokIM up and running.
That includes installing backend dependencies, installing frontend dependencies, building frontend and then running the LokIM server.
It would be much smoother if first LokIM run would consist of 2 commands.
One to prepare the codebase - which consists installing dependencies and bundling frontend.
An second to just start the LokIM.

**User story**
1. I'm an user or developer, and I enter the github page of the LokIM.
2. I clone the project
3. I run a command that deploys the code for me
4. I run a command to start the LokIM server
5. My application is up and running

### PR DESCRIPTION
**Pull request by obsceniczny**
**Reference to related ticket:**
Resolves #135 
**Description of changes:**

### CODE REVIEW

**Comment by obsceniczny** [comment]
@Jordan141 
@MarcinGrzeszczak 
please review

**Comment by michaelKurowski** [comment]
The CI issue will be solved with this PR:
https://github.com/michaelKurowski/lokim2/pull/163

**Comment by michaelKurowski** [comment]
Fyi CI fixed. Please rebase with master

**Comment by michaelKurowski** [comment]
Retry Deepcode

**Pull request merged**
