### PR TITLE
#142 Store Chat History

### LINKED ISSUE #142: Store chat history
**Is your feature request related to a problem? Please describe.**
User can't see his history after re-logging.

**Describe the solution you'd like**
We should store chat history both server-side, and client-side. All the messages and opened conversations should be stored.
Messages should be stored in `messages` collection, with the following format:
```
{
   author: username,
   room: id,
   text: "blabla",
   date: unix timestamp
}
```
Messages history should be sent to user upon login.
**Describe alternatives you've considered**
Not storing chat history at all. Storing it server-side only.

**User story**
1. User goes into a room
2. User receives a messages

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Jordan141**
**Reference to related ticket:**
 resolves #142 

**Description of changes:**
This PR will make it so that the room chat data is stored on the server.
In a later update, this will be encrypted.

In the current version of this setup, chat data will only be sent out upon the initial join of the room.

#### Flow of logic

- User sends a message

- Server receives the message

- Server appends this message to Room's array of messages

- Server directs the message to all users of the chat

  ------

- New user joins
- New user fires off the event requesting the previous chat history.
- New user receives all previous messages (LATER: *up to a certain date)

Security concern: Add logic so that only users currently in the room can request chat data for said room.

### CODE REVIEW

**Comment by Jordan141** [comment]
I believe we should add the list of users in the room to the Room object in the database. I'm aware that we currently have a working solution to this problem, however this was developed when we were still trying to avoid storing anything on the server.

Pros:
- Ease of use.
- Makes accessing data simpler.
- We also won't lose userlist on a server restart.
- Avoid security vulnerabilities as mentioned above.
- Improves maintainability as well as scalability. 

Cons:
- Major change to current inner workings of the socket system.
- May be enough work to warrant it's own PR.

I will not be making any more changes in this direction until we have discussed it thoroughly.

**Comment by Jordan141** [comment]
TODO: 
- Rename my "room controller" to avoid ambiguity

**Comment by michaelKurowski** [comment]
Why did you created a new room controller? @Jordan141

**Comment by michaelKurowski** [comment]
Is everything good with your PR @Jordan141 it seems that you want to commit some weird changes

**Comment by michaelKurowski** [comment]
@Jordan141 bump

**Pull request closed without merging**
